### ISSUE TITLE
Could not pass event PlayerInteractEntityEvent to UVVillagers v1.3.1

### ISSUE THREAD

**Issue by SulpherStaer** [jcornwellshiel/uvvillagers#43]
2013-07-18 09:17:04 [SEVERE] Could not pass event PlayerInteractEntityEvent to UVVillagers v1.3.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:46)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
    at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:1114)
    at net.minecraft.server.v1_6_R2.Packet7UseEntity.handle(SourceFile:36)
    at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:235)
    at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:118)
    at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
    at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:125)
    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:592)
    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:239)
    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:481)
    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:413)
    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: java.lang.NullPointerException
    at net.uvnode.uvvillagers.UVVillagers.onPlayerInteractEntityEvent(UVVillagers.java:773)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 15 more

**Comment by jcornwellshiel** [comment]
I'll be committing a fix to this tonight.

**Comment by SulpherStaer** [comment]
Wonderful! - sadly I won't be able to run / test it tonight, tomorrow though!

I really love this plugin, it has totally increased the use of villagers / villages!

**Comment by jcornwellshiel** [comment]
Confirmed fixed in latest versions.
