### ISSUE TITLE
event.EventException spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370

### ISSUE THREAD

**Issue by Bannta** [jcornwellshiel/uvvillagers#50]
Mayor's react as villagers in 1.7.5 and tons of the below errors.

[13:33:20] [Server thread/ERROR]: Could not pass event UVTimeEvent to UVVillagers v1.3.8
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    at net.uvnode.uvvillagers.UVVillagers$1.run(UVVillagers.java:267) [UVVillagers-1.3.8-dev.jar:?]
    at org.bukkit.craftbukkit.v1_7_R2.scheduler.CraftTask.run(CraftTask.java:58) [spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    at org.bukkit.craftbukkit.v1_7_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    at net.minecraft.server.v1_7_R2.MinecraftServer.v(MinecraftServer.java:618) [spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    at net.minecraft.server.v1_7_R2.DedicatedServer.v(DedicatedServer.java:273) [spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    at net.minecraft.server.v1_7_R2.MinecraftServer.u(MinecraftServer.java:566) [spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:472) [spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618) [spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_7_R1/CraftWorld
    at net.uvnode.uvvillagers.VillageManager.getClosestCoreVillageToLocation(VillageManager.java:51) ~[?:?]
    at net.uvnode.uvvillagers.VillageManager.updatePlayerProximity(VillageManager.java:546) ~[?:?]
    at net.uvnode.uvvillagers.VillageManager.checkPlayerProximities(VillageManager.java:533) ~[?:?]
    at net.uvnode.uvvillagers.UVVillagers.onUVTimeEvent(UVVillagers.java:813) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[spigot-1.7.5-R0.1-SNAPSHOT.jar:git-Spigot-1370]
    ... 12 more

**Comment by jcornwellshiel** [comment]
I haven't compiled it for 1.7.5 yet. I'll do that tonight.
